### PR TITLE
Feature show/insert inferred types

### PR DESCRIPTION
**Pull request by rohanorton**
Hi,

I wrote a couple of functions that either echo or insert the inferred type signature for the function under the cursor, like `_t` and `_T` in haskellmode-vim plugin.

 Apologies in advance, my vimscript skills are pretty shoddy :(

### CODE REVIEW

**Comment by lorenzo** [comment]
I tried this locally, but it shows wrong string... like a single closing parenthesis, for example

**Comment by maximsch2** [comment]
Can this also take type from elm-make warnings that suggest it? Atom's Elm integration has this feature (quick fix)

**Comment by lorenzo** [comment]
@maximsch2 that's already working in elm-vim

**Comment by rohanorton** [comment]
@lorenzo Cheers for mentioning. I'll have a look into it. Presuming this is for types that take up multiple lines.

**Comment by lorenzo** [comment]
I tried it for a normal `update` function... removed the type definition and ran the function, and all I got was a `)`

**Comment by maximsch2** [comment]
@lorenzo I haven't realized that. How do I trigger it?

**Comment by lorenzo** [comment]
@maximsch2 add this to your vimrc

```viml
let g:elm_syntastic_show_warnings = 1
```

**Comment by maximsch2** [comment]
I have that. What I meant is that Atom, in addition to showing the warning itself, also proposes to apply the fix for you (it will just copy and paste the type from the warning into your file). Is it possible with elm-vim? Seems related to this PR.

**Comment by lorenzo** [comment]
ah, sorry @maximsch2  I did not understand what you meant. Thats not currently possible, but I think it is doable

**Comment by maximsch2** [comment]
Exactly. I think this PR is essentially trying to do that. Note that there are some issues with it:
- It will only show/insert types when they are missing, as it will run the same elm-make script to look for missing type erros. This means that having a quickfix option from the window will be preferred as we won't have to spawn another elm-make that way.
- It won't be able to show types for any object under cursor (at least as far as I can understand the code). For that we should probably use elm-oracle.

**Comment by rohanorton** [comment]
@lorenzo , I think I've sorted out multiline signatures now if you want to try.

Thoughts...

It only works properly when run after a file save. I am thinking that perhaps i should save the file every time the function is invoked, but that feels a bit wrong to me. What's would you suggest?

**Comment by maximsch2** [comment]
@rohanorton why can't you just pull it out of warnings window? The information is there for sure (it is can be seen when asking for error detail) and it is in the same format probably.

**Comment by rohanorton** [comment]
@maximsch2 hm, that may well be a possibility, but it's not going to work for people who don't have syntastic (e.g. me)

**Comment by maximsch2** [comment]
@rohanorton Right, I haven't realized that the warnings window was dependent on syntastic. Running full-blown elm-make on each type inference seems a bit excessive, but it looks like even Elm-Oracle 2.0 (https://github.com/ElmCast/elm-oracle/issues/13) won't be able to infer those types so it might be the only way to do it.

**Pull request closed without merging**
