### PR TITLE
Fix mappings

### PR DESCRIPTION
**Pull request by KevinSjoberg**
The current implementation was not working, this refactors the key
mappings according to best practices.

### CODE REVIEW

**Comment by KevinSjoberg** [comment]
Any chance we can get this merged?

**Comment by ajhager** [comment]
Could you please describe in more detail what issue this fixes, so I know how to test this PR? You say the keymappings were not working, but they seem to have been working for everyone else up until now. What specifically wasn't working for you, which version of Vim / NeoVim, which platform, is there a way to reproduce your issues easily?

Thank you for your hard work.

**Comment by KevinSjoberg** [comment]
@ajhager absolutely. Sorry for not providing more details upfront.

So, I'm running Neovim, version `0.1.4`. The suggested keymappings was not working at all for me. The defined autocommands were indeed executed, but had no effect.

First of all, I moved out the mapping definitions to `plugin/elm.vim`. This have no effect for the problem I was having but it's standard practice to define `<Plug>` mappings in `plugin/x.vim` so that the mappings are globally available for power users and other VimScript developers.

Secondly, I removed the autocommands and redefined the mappings as buffer local commands.This is also standard practice. See "FileType Events" in http://learnvimscriptthehardway.stevelosh.com/chapters/12.html.

These mappings can not have been working for anyone else since they got moved from the `README` into the `ftplugin/elm.vim` file. The `ftplugin/elm.vim` file is executed as you open a new file and thus the defined autocommands are not triggered. You would have to reopen another file for this to take effect.

If anything is unclear, don't hesitate to ask. I'm not experienced with VimScript at all so feel free to question any change I made. 😄

**Comment by ajhager** [comment]
The mapping work fine for me before this patch, but with it they stop working completely. I will investigate your changes more, and check out the link you provided. Hopefully we can find a solution that is correct on both of our computers.

**Comment by KevinSjoberg** [comment]
@ajhager make sure that you've set `maplocalleader` to the same key as your `mapleader`.

**Pull request merged**
